name: Build Kivy Android App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with official Kivy action
        uses: kivy/build-kivy-action@v1
        with:
          # Aquí le decimos qué comando ejecutar
          run: |
            buildozer -v android debug

          # Aquí le decimos dónde encontrar el APK
          apk_path: "bin/*.apk"
